/**
 * Copy of `www/hub/config.js` `TAG_RULES` — keep in sync when hub taxonomy changes.
 */
export type TagRule = { tag: string; kw: string[] };

export const TAG_RULES: TagRule[] = [
  {
    tag: 'DSP',
    kw: [
      'dsp',
      'demand-side',
      'demand side',
      'madhive',
      'mntn',
      'bidtheatre',
      'splicky',
      'xandr',
      'thetradedesk',
      'criteo',
      'stackadapt',
      'liquid advertising',
    ],
  },
  {
    tag: 'SSP',
    kw: [
      'ssp',
      'supply-side',
      'supply side',
      'pubmatic',
      'equativ',
      'openx',
      'sharethrough',
      'sovrn',
      'scoota',
    ],
  },
  {
    tag: 'Agency',
    kw: ['agency', 'havas', 'dentsu', 'omd', 'publicis', 'wpp', 'omg', 'interpublic', 'media buy'],
  },
  {
    tag: 'Data',
    kw: [
      'data provider',
      'data exchange',
      'data platform',
      'datonics',
      'mobilewalla',
      'globaldata',
      'global data',
      'true data',
      'epsilon',
      'experian',
      'nielsen',
      'claritas',
      'precisely',
      'ventiveiq',
      'weborama',
      'beklever',
    ],
  },
  {
    tag: 'Identity',
    kw: ['cookieless', 'identity', 'id5', 'liveramp', 'tapad', 'kochava', 'bango'],
  },
  {
    tag: 'CDP/DMP',
    kw: ['dmp', 'cdp', 'adobe', 'zeotap', 'permutive', 'lotame', 'semasio', 'audigent'],
  },
  { tag: 'CTV', kw: ['ctv', 'connected tv', 'vistar', 'mntn', 'madhive', 'samba', 'aniview'] },
  {
    tag: 'Mobile',
    kw: ['mobile', 'moboost', 'memob', 'anzu', 'kochava', 'bango', 'intuizi', 'opensignal'],
  },
  {
    tag: 'Marketplace',
    kw: ['marketplace', 'curation', 'liveramp', 'audigent', 'equativ', 'sharethrough', 'pubmatic'],
  },
  {
    tag: 'EU/EMEA',
    kw: [
      'europe',
      'european',
      'emea',
      'scandinavia',
      'spain',
      'poland',
      ' pl ',
      'germany',
      'france',
      'uk',
      'netherlands',
      'sweden',
      'nordic',
      'adform',
      'bidtheatre',
      'eskimi',
      'belogic',
      'beintoo',
      'eyeota',
      'weborama',
    ],
  },
  {
    tag: 'US',
    kw: [
      'usa',
      'north america',
      'datonics',
      'claritas',
      'epsilon',
      'foursquare',
      'mastercard',
      'oracle',
      'samba tv',
      'madhive',
      'mntn',
      'stackadapt',
    ],
  },
  {
    tag: 'APAC',
    kw: [
      'apac',
      'asia',
      'thailand',
      'china',
      'india',
      'japan',
      'australia',
      'bytedance',
      'tiktok',
      'dentsu thailand',
      'omd thailand',
    ],
  },
  { tag: 'Retail/OOH', kw: ['retail', 'wowcher', 'ooh', 'out-of-home', 'foursquare', 'vistar'] },
  {
    tag: 'Programmatic',
    kw: [
      'programmatic',
      'rtb',
      'bidder',
      'exchange',
      'trading desk',
      'bidberry',
      'bidscube',
      'hybrid',
    ],
  },
  {
    tag: 'Research',
    kw: [
      'research',
      'analytics',
      'insights',
      'sportradar',
      'national research',
      'big village',
      'dynata',
      'echo analytics',
    ],
  },
];
